[package]
name = "dossier-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dossier-beatmap = { path = "../dossier-beatmap" }
dossier-replay = { path = "../dossier-replay" }
dossier-sim = { path = "../dossier-sim" }
tiny-skia = "0.11"
fontdue = "0.9"
